name : 'Get Changed Files'
description : 'Get the changed files in a pull request or push commits'
author : 'Coke.com'

inputs :
  github_token : 
    required: true
    description: 'Github token to make API requests'
  base_ref : 
    description : 'The base commit or target commit of the pull request in a workflow run'
  head_ref : 
    description : 'The merge commit created by github to test test whether the pull request can be automatically merged into the base branch.'
  client_id:
    description : 'Ouath client ID (Consumer key of the connected app)'
  user_name:
    description : 'Authentication username'
  jwt_key_file : 
    description : 'Path to a file containing the private key'
  instance_url :
    description : 'login URL of the instance to connect'
    
outputs : 
  all : 
    description : 'JSON string with all changed files'
  added :
    description : 'JSON string with only files added'  
  deleted : 
    description : 'JSON string with only files deleted'
  modified :
    description : 'JSON string with only files modified'
  renamed :
    description : 'JSON string with only files renamed'
  changed :
    description : 'JSON string with only files with type (i.e. regular file, symlink, submodule)'

runs:
  using: 'node12'
  main: 'dist/index.js'
